ALTER TABLE branches ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE branches ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE organizations ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE organizations ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE projects ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE projects ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE memberships ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE memberships ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();

DROP TABLE endpoints;
DROP TYPE endpoint_state;
