# TYPE  DATABASE  USER          ADDRESS       METHOD
local   all       cloud_admin                 trust
host    all       cloud_admin   127.0.0.1/32  trust
host    all       cloud_admin   ::1/32        trust
hostssl all       cloud_admin   all           scram-sha-256
hostssl all       neond         all           scram-sha-256
host    all       all           all           scram-sha-256